sudo: required

language: go

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - curl
      - python-dev
      - python3-pip
      - python3

script:
  - ./build
